version: "3.9"
services:
  worker:
    build: .
    environment:
      APP_ID: $APP_ID
      API_HASH: $API_HASH
      TG_BOT_TOKEN: $TG_BOT_TOKEN
      AUTH_CHANNEL: $AUTH_CHANNEL
      OWNER_ID: $OWNER_ID